packages:
  - 'apps/*'

allowBuilds:
  core-js: set this to true or false
  esbuild: set this to true or false
minimumReleaseAgeExclude:
  - '@rtorcato/js-tooling@2.19.1'
onlyBuiltDependencies:
  - esbuild
